=begin
#OpenSearch

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2021-11-23

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/action_object_structure'
require 'openapi_client/models/default_operator'
require 'openapi_client/models/delete_index_response_content'
require 'openapi_client/models/expand_wildcards'
require 'openapi_client/models/get_cluster_info_response_content'
require 'openapi_client/models/get_cluster_settings_response_content'
require 'openapi_client/models/get_document_doc_response_content'
require 'openapi_client/models/health_status'
require 'openapi_client/models/hits'
require 'openapi_client/models/hits_metadata'
require 'openapi_client/models/post_aliases_request_content'
require 'openapi_client/models/post_aliases_response_content'
require 'openapi_client/models/post_search_request_content'
require 'openapi_client/models/post_search_response_content'
require 'openapi_client/models/post_search_with_index_request_content'
require 'openapi_client/models/post_search_with_index_response_content'
require 'openapi_client/models/put_create_index_request_content'
require 'openapi_client/models/put_create_index_response_content'
require 'openapi_client/models/put_index_mapping_with_index_request_content'
require 'openapi_client/models/put_index_mapping_with_index_response_content'
require 'openapi_client/models/put_update_cluster_settings_request_content'
require 'openapi_client/models/put_update_cluster_settings_response_content'
require 'openapi_client/models/relation'
require 'openapi_client/models/search_type'
require 'openapi_client/models/shard_statistics'
require 'openapi_client/models/suggest_mode'
require 'openapi_client/models/total'
require 'openapi_client/models/user_defined_object_structure'
require 'openapi_client/models/user_defined_structure'
require 'openapi_client/models/version'
require 'openapi_client/models/version_type'

# APIs
require 'openapi_client/api/default_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
