=begin
#OpenSearch

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2021-11-23

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::PostAliasesRequestContent
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::PostAliasesRequestContent do
  let(:instance) { OpenapiClient::PostAliasesRequestContent.new }

  describe 'test an instance of PostAliasesRequestContent' do
    it 'should create an instance of PostAliasesRequestContent' do
      expect(instance).to be_instance_of(OpenapiClient::PostAliasesRequestContent)
    end
  end
  describe 'test attribute "actions"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
