=begin
#OpenSearch

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2021-11-23

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::PutUpdateClusterSettingsRequestContent
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::PutUpdateClusterSettingsRequestContent do
  let(:instance) { OpenapiClient::PutUpdateClusterSettingsRequestContent.new }

  describe 'test an instance of PutUpdateClusterSettingsRequestContent' do
    it 'should create an instance of PutUpdateClusterSettingsRequestContent' do
      expect(instance).to be_instance_of(OpenapiClient::PutUpdateClusterSettingsRequestContent)
    end
  end
  describe 'test attribute "persistent"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "transient"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
