=begin
#OpenSearch

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2021-11-23

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::SuggestMode
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::SuggestMode do
  let(:instance) { OpenapiClient::SuggestMode.new }

  describe 'test an instance of SuggestMode' do
    it 'should create an instance of SuggestMode' do
      expect(instance).to be_instance_of(OpenapiClient::SuggestMode)
    end
  end
end
