=begin
#OpenSearch

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2021-11-23

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::DefaultApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::DefaultApi)
    end
  end

  # unit tests for delete_index
  # Removes a document from the index.
  # @param index 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :master_timeout 
  # @option opts [String] :cluster_manager_timeout 
  # @option opts [Boolean] :allow_no_indices 
  # @option opts [ExpandWildcards] :expand_wildcards 
  # @option opts [Boolean] :ignore_unavailable 
  # @option opts [String] :timeout 
  # @return [DeleteIndexResponseContent]
  describe 'delete_index test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_cat_indices
  # Returns information about indices: number of primaries and replicas, document counts, disk size, etc.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :master_timeout 
  # @option opts [String] :cluster_manager_timeout 
  # @option opts [Integer] :bytes 
  # @option opts [ExpandWildcards] :expand_wildcards 
  # @option opts [HealthStatus] :health 
  # @option opts [Boolean] :include_unloaded_segments 
  # @option opts [Boolean] :pri 
  # @option opts [String] :time 
  # @option opts [String] :format 
  # @return [Object]
  describe 'get_cat_indices test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_cat_indices_with_index
  # Returns information about indices: number of primaries and replicas, document counts, disk size, etc.
  # @param index 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :master_timeout 
  # @option opts [String] :cluster_manager_timeout 
  # @option opts [Integer] :bytes 
  # @option opts [ExpandWildcards] :expand_wildcards 
  # @option opts [HealthStatus] :health 
  # @option opts [Boolean] :include_unloaded_segments 
  # @option opts [Boolean] :pri 
  # @option opts [String] :time 
  # @option opts [String] :format 
  # @return [Object]
  describe 'get_cat_indices_with_index test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_cat_nodes
  # Returns basic statistics about performance of cluster nodes.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :master_timeout 
  # @option opts [String] :cluster_manager_timeout 
  # @option opts [Integer] :bytes 
  # @option opts [Boolean] :full_id 
  # @option opts [Boolean] :local 
  # @option opts [String] :time 
  # @option opts [Boolean] :include_unloaded_segments 
  # @option opts [String] :format 
  # @return [Object]
  describe 'get_cat_nodes test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_cluster_info
  # Returns whether the cluster is running.
  # @param [Hash] opts the optional parameters
  # @return [GetClusterInfoResponseContent]
  describe 'get_cluster_info test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_cluster_settings
  # Returns cluster settings.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :master_timeout 
  # @option opts [String] :cluster_manager_timeout 
  # @option opts [Boolean] :flat_settings 
  # @option opts [Boolean] :include_defaults 
  # @return [GetClusterSettingsResponseContent]
  describe 'get_cluster_settings test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_document_doc
  # Returns a document
  # @param index 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :preference 
  # @option opts [Boolean] :realtime 
  # @option opts [Boolean] :refresh 
  # @option opts [String] :routing 
  # @option opts [Boolean] :stored_fields 
  # @option opts [String] :_source 
  # @option opts [String] :_source_excludes 
  # @option opts [String] :_source_includes 
  # @option opts [Integer] :version 
  # @option opts [VersionType] :version_type 
  # @return [GetDocumentDocResponseContent]
  describe 'get_document_doc test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_document_source
  # Returns a document.
  # @param index 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :preference 
  # @option opts [Boolean] :realtime 
  # @option opts [Boolean] :refresh 
  # @option opts [String] :routing 
  # @option opts [Boolean] :stored_fields 
  # @option opts [String] :_source 
  # @option opts [String] :_source_excludes 
  # @option opts [String] :_source_includes 
  # @option opts [Integer] :version 
  # @option opts [VersionType] :version_type 
  # @return [nil]
  describe 'get_document_source test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_settings_index
  # The get settings API operation returns all the settings in your index.
  # @param index 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :master_timeout 
  # @option opts [String] :cluster_manager_timeout 
  # @option opts [Boolean] :allow_no_indices 
  # @option opts [ExpandWildcards] :expand_wildcards 
  # @option opts [Boolean] :flat_settings 
  # @option opts [String] :include_defaults 
  # @option opts [Boolean] :ignore_unavailable 
  # @option opts [Boolean] :local 
  # @return [Object]
  describe 'get_settings_index test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_settings_index_setting
  # The get settings API operation returns all the settings in your index.
  # @param index 
  # @param setting 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :master_timeout 
  # @option opts [String] :cluster_manager_timeout 
  # @option opts [Boolean] :allow_no_indices 
  # @option opts [ExpandWildcards] :expand_wildcards 
  # @option opts [Boolean] :flat_settings 
  # @option opts [String] :include_defaults 
  # @option opts [Boolean] :ignore_unavailable 
  # @option opts [Boolean] :local 
  # @return [Object]
  describe 'get_settings_index_setting test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_aliases
  # Adds or removes index aliases.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :master_timeout 
  # @option opts [String] :cluster_manager_timeout 
  # @option opts [String] :timeout 
  # @option opts [PostAliasesRequestContent] :post_aliases_request_content 
  # @return [PostAliasesResponseContent]
  describe 'post_aliases test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_search
  # Returns results matching a query.
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :allow_no_indices 
  # @option opts [Boolean] :allow_partial_search_results 
  # @option opts [String] :analyzer 
  # @option opts [Boolean] :analyze_wildcard 
  # @option opts [Integer] :batched_reduce_size 
  # @option opts [Boolean] :ccs_minimize_roundtrips 
  # @option opts [DefaultOperator] :default_operator 
  # @option opts [String] :df 
  # @option opts [String] :docvalue_fields 
  # @option opts [ExpandWildcards] :expand_wildcards 
  # @option opts [Boolean] :explain 
  # @option opts [Integer] :from 
  # @option opts [Boolean] :ignore_throttled 
  # @option opts [Boolean] :ignore_unavailable 
  # @option opts [Boolean] :lenient 
  # @option opts [Integer] :max_concurrent_shard_requests 
  # @option opts [Integer] :pre_filter_shard_size 
  # @option opts [String] :preference 
  # @option opts [String] :q 
  # @option opts [Boolean] :request_cache 
  # @option opts [Boolean] :rest_total_hits_as_int 
  # @option opts [String] :routing 
  # @option opts [String] :scroll 
  # @option opts [SearchType] :search_type 
  # @option opts [Boolean] :seq_no_primary_term 
  # @option opts [Integer] :size 
  # @option opts [Array<String>] :sort 
  # @option opts [String] :source 
  # @option opts [Array<String>] :source_excludes 
  # @option opts [Array<String>] :source_includes 
  # @option opts [String] :stats 
  # @option opts [Boolean] :stored_fields 
  # @option opts [String] :suggest_field 
  # @option opts [SuggestMode] :suggest_mode 
  # @option opts [Integer] :suggest_size 
  # @option opts [String] :suggest_text 
  # @option opts [Integer] :terminate_after 
  # @option opts [String] :timeout 
  # @option opts [Boolean] :track_scores 
  # @option opts [Integer] :track_total_hits 
  # @option opts [Boolean] :typed_keys 
  # @option opts [Boolean] :version 
  # @option opts [PostSearchRequestContent] :post_search_request_content 
  # @return [PostSearchResponseContent]
  describe 'post_search test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_search_with_index
  # Returns results matching a query.
  # @param index 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :allow_no_indices 
  # @option opts [Boolean] :allow_partial_search_results 
  # @option opts [String] :analyzer 
  # @option opts [Boolean] :analyze_wildcard 
  # @option opts [Integer] :batched_reduce_size 
  # @option opts [Boolean] :ccs_minimize_roundtrips 
  # @option opts [DefaultOperator] :default_operator 
  # @option opts [String] :df 
  # @option opts [String] :docvalue_fields 
  # @option opts [ExpandWildcards] :expand_wildcards 
  # @option opts [Boolean] :explain 
  # @option opts [Integer] :from 
  # @option opts [Boolean] :ignore_throttled 
  # @option opts [Boolean] :ignore_unavailable 
  # @option opts [Boolean] :lenient 
  # @option opts [Integer] :max_concurrent_shard_requests 
  # @option opts [Integer] :pre_filter_shard_size 
  # @option opts [String] :preference 
  # @option opts [String] :q 
  # @option opts [Boolean] :request_cache 
  # @option opts [Boolean] :rest_total_hits_as_int 
  # @option opts [String] :routing 
  # @option opts [String] :scroll 
  # @option opts [SearchType] :search_type 
  # @option opts [Boolean] :seq_no_primary_term 
  # @option opts [Integer] :size 
  # @option opts [Array<String>] :sort 
  # @option opts [String] :source 
  # @option opts [Array<String>] :source_excludes 
  # @option opts [Array<String>] :source_includes 
  # @option opts [String] :stats 
  # @option opts [Boolean] :stored_fields 
  # @option opts [String] :suggest_field 
  # @option opts [SuggestMode] :suggest_mode 
  # @option opts [Integer] :suggest_size 
  # @option opts [String] :suggest_text 
  # @option opts [Integer] :terminate_after 
  # @option opts [String] :timeout 
  # @option opts [Boolean] :track_scores 
  # @option opts [Integer] :track_total_hits 
  # @option opts [Boolean] :typed_keys 
  # @option opts [Boolean] :version 
  # @option opts [PostSearchWithIndexRequestContent] :post_search_with_index_request_content 
  # @return [PostSearchWithIndexResponseContent]
  describe 'post_search_with_index test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_create_index
  # Creates index mappings.
  # @param index 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :master_timeout 
  # @option opts [String] :cluster_manager_timeout 
  # @option opts [Boolean] :include_type_name 
  # @option opts [String] :wait_for_active_shards 
  # @option opts [String] :timeout 
  # @option opts [PutCreateIndexRequestContent] :put_create_index_request_content 
  # @return [PutCreateIndexResponseContent]
  describe 'put_create_index test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_index_mapping_with_index
  # The put mapping API operation lets you add new mappings and fields to an index.
  # @param index 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :master_timeout 
  # @option opts [String] :cluster_manager_timeout 
  # @option opts [Boolean] :allow_no_indices 
  # @option opts [ExpandWildcards] :expand_wildcards 
  # @option opts [Boolean] :ignore_unavailable 
  # @option opts [Boolean] :include_type_name 
  # @option opts [String] :timeout 
  # @option opts [Boolean] :write_index_only 
  # @option opts [PutIndexMappingWithIndexRequestContent] :put_index_mapping_with_index_request_content 
  # @return [PutIndexMappingWithIndexResponseContent]
  describe 'put_index_mapping_with_index test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_update_cluster_settings
  # Updates the cluster settings.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :master_timeout 
  # @option opts [String] :cluster_manager_timeout 
  # @option opts [Boolean] :flat_settings 
  # @option opts [String] :timeout 
  # @option opts [PutUpdateClusterSettingsRequestContent] :put_update_cluster_settings_request_content 
  # @return [PutUpdateClusterSettingsResponseContent]
  describe 'put_update_cluster_settings test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
